# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

r:
 - oldrel
 - release
 - devel

# codecov
r_packages:
  - covr

# report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
